#!/usr/bin/env bash

clear
printf "\033[35mGit Cheat Sheet\033[0m\n\n"
printf "\033[36mCheck state\033[0m\n"
printf "  git status --short --branch\n"
printf "  git diff\n"
printf "  git diff --staged\n"
printf "  git log --oneline --graph --decorate -12\n"
printf "\n\033[36mStage and commit\033[0m\n"
printf "  git add <file>\n"
printf "  git add -A\n"
printf "  git restore --staged <file>\n"
printf "  git commit -m \"what changed\"\n"
printf "\n\033[36mBranches\033[0m\n"
printf "  git switch <branch>\n"
printf "  git switch -c my-branch\n"
printf "  git branch -vv\n"
printf "\n\033[36mSync\033[0m\n"
printf "  git pull --ff-only\n"
printf "  git push\n"
printf "  git push -u origin HEAD\n"
printf "\n\033[36mUndo / park work\033[0m\n"
printf "  git restore <file>\n"
printf "  git restore --source=HEAD -- <file>\n"
printf "  git stash push -m \"note\"\n"
printf "  git stash pop\n"
printf "\n\033[36mUsual flow\033[0m\n"
printf "  status -> diff -> add -> diff --staged -> commit -> push\n"
printf "\n\033[38;5;244mThis pane stays usable after printing.\033[0m\n\n"
